services:
  backend-parking-availability:
    container_name: backend-parking-availability-container
    build: .
    ports:
      - "8004:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
